// <auto-generated />
using ManyToMany2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManyToMany2.Migrations
{
    [DbContext(typeof(PCContext))]
    [Migration("20240430140853_migrationPCC")]
    partial class migrationPCC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManyToMany2.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("ManyToMany2.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("ManyToMany2.Models.ProjetConsultant", b =>
                {
                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultantId")
                        .HasColumnType("int");

                    b.HasKey("ProjetId", "ConsultantId");

                    b.HasIndex("ConsultantId");

                    b.ToTable("ProjetConsultants");
                });

            modelBuilder.Entity("ManyToMany2.Models.ProjetConsultant", b =>
                {
                    b.HasOne("ManyToMany2.Models.Consultant", "Consultant")
                        .WithMany("ProjetConsultant")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManyToMany2.Models.Projet", "Projet")
                        .WithMany("ProjetConsultant")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("ManyToMany2.Models.Consultant", b =>
                {
                    b.Navigation("ProjetConsultant");
                });

            modelBuilder.Entity("ManyToMany2.Models.Projet", b =>
                {
                    b.Navigation("ProjetConsultant");
                });
#pragma warning restore 612, 618
        }
    }
}
